noun = input("Enter a noun:")
adjective = input("Enter an adjective:")
adverb = input("Enter an adverb:")
verb= input("Enter a verb:")
print("On a", adjective, "island,Underneath a", adverb,  "lava moon. Hangin' with the hula", noun + " Askin' questions cause' they", verb,  "all the answers.")
