noun = prompt("Enter a noun:")
adjective = prompt("Enter an adjective:")
adverb = prompt("Enter an adverb:")
verb= prompt("Enter a verb:")
input("On a", adjective, "island,Underneath a", adverb,  "lava moon. Hangin' with the hula", noun + " Askin' questions cause' they", verb,  "all the answers.")
